notifications:
  email:
  - ndrone@gmail.com
language: java
jdk:
- oraclejdk8
addons:
  sonarqube:
    token:
      secure: e3obhk2IKreggUUlzB1AsvYEr7MiwdgkSSeQuv1m/UgPnSv2V1ymCD+3S2Y+95C58wG4/7ZZnUkd+sdr3TMu4xE3E/sfBx4np5s0LgkUbP9NiOJ0tomBUZyW3G6EJRj2H6fc+Ic3xJv7GVlrqTY9m2fTdXSt9weVC6+3tTBI3lo1HMJ5SQjIfl8ZSmRomEXwxvOKI6SR7B4RikChQ9u0uGd0bThjAQKnTILdxMb4m1Vn4q7wICiGpDLGgcL41XwfFk5XNiPFN5TvO73sRMMVZ9q6my1UzbMBJPOC3ok2Mg1giU8cEEyOBuy02kowRiCqoaPYJxRa3tgkX9HextVQ4Qdz8zdSmctnxA/6IgWBBivAhO0JsQakMUeRusfgd/kzK4rf7m12a6Z6BnXSkx2fY3/KFwRHHnYPqpDiAHG1easznLmMtIqoamcYeUu4UuPv4lrDCUK08bd0MY7vj7X9AYdGr5g/HPEgmG+bxe25tTBJJ/20DkrUWKDka36hDGKfAFmgzMR3k9voI43ExPPfnaDbTvyWIOF39SimmUYowNbk0kRqHkrsrwfbrujo73aX+0adqOTquuzeQKCTWWY1KSJjLkcWU49KZ9zxskANhb/gkD5Z6hgtIRsz00I5p3e6VSjTyvtDKNZEPSh0GSN1HDLEqhZXgcMavxMjcaXL/0M=
    github_token:
      secure: JkKQLI5IyNJ47w8vwhO6fIduRouVK0pVIE1fXGZed94ZqrrTv538V+2pm/uu+f8/6WEkaHqsMX3kXCRsxTLFOG9v7AucqLA2yoPud6AwSgsxb5C0VjI8TkebuMoUL3LYGM9xd0iRemJ0V73GY5iGbRPtX+RTjG4PxpODFl4y0DMbDvdT//Yr6dbr0CvHnKCG1DtXA8cs2Vs/HAikyW1n7llKLHlS09Y5lsstzKH6duGO6nfTIE9+0ExkHTt7t3b6AVXDmbh2VcRpDNN67E2R26Vg8FeVObZgfBd/J7nWL87HuTrvhgtL7XsCZioSOrUXrp2aK4vtVtWDy/5ei0WnXCSyr3/NqrHOEYI0eouvsasp0wv8DjKX2i5/K00YVQZgg40CCXgQCove5aJ9z8bOQ55tzjwHTHGEkaexMcEivB0yV18OY87aJSZJVVYfowq2a0OihrhilvieJUnewRjXcjPSdswMcinKOR0ahX1v01EG48HXBWFjNtRk4lV2xwxfRG1ARq3RrUP7goDm5jA6K5rPa7vMUu9ynwL/v5sEjzunHYsw/3Bdtau0S0hU8rxFnCP0x28pGDpHgZ2meR302oZkzCvoiUlQqs1NI1372opjIVZwjnHKt4gacpi9uMLrsKsguCukqBu0Z1D0QjS+zzWFdPjNri0iFbfRnED6bQg=
  branches:
  - master
  - develop
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
